"""Canonical mapping utilities for Twilight Struggle card names and countries."""

import ts_engine as ts
from typing import Dict

# Canonical mapping from card slugs to Twilight Struggle Card IDs (1..110)
CANONICAL_CARD_SLUG_TO_ID: Dict[str, int] = {
    "asia": 1,
    "asiascoring": 1,
    "europe": 2,
    "europescoring": 2,
    "mideast": 3,
    "mideastscoring": 3,
    "middleeastscoring": 3,
    "duckandcover": 4,
    "fiveyearplan": 5,
    "thechinacard": 6,
    "chinacard": 6,
    "socgov": 7,
    "socialistgovernments": 7,
    "fidel": 8,
    "vietnamrevolts": 9,
    "blockade": 10,
    "koreanwar": 11,
    "romanianab": 12,
    "romanianabdication": 12,
    "arabisraeli": 13,
    "arabisraeliwar": 13,
    "comecon": 14,
    "nasser": 15,
    "warsawpact": 16,
    "warsawpactformed": 16,
    "degaulle": 17,
    "degualle": 17,
    "degaulleleadsfrance": 17,
    "naziscientist": 18,
    "capturednaziscientist": 18,
    "truman": 19,
    "trumandoctrine": 19,
    "olympic": 20,
    "olympicgames": 20,
    "nato": 21,
    "indreds": 22,
    "independentreds": 22,
    "marshall": 23,
    "marshallplan": 23,
    "indopaki": 24,
    "indopakistaniwar": 24,
    "containment": 25,
    "cia": 26,
    "ciacreated": 26,
    "usjapan": 27,
    "usjapanmutualdefensepact": 27,
    "suezcrisis": 28,
    "easteuropean": 29,
    "easteuropeanunrest": 29,
    "decolonization": 30,
    "redscare": 31,
    "redscarepurge": 31,
    "unintervention": 32,
    "destalinization": 33,
    "nucleartestban": 34,
    "formosan": 35,
    "formosanresolution": 35,
    "brushwar": 36,
    "camerica": 37,
    "centralamerica": 37,
    "centralamericascoring": 37,
    "seasia": 38,
    "southeastasiascoring": 38,
    "armsrace": 39,
    "cubanmissile": 40,
    "cubanmissilecrisis": 40,
    "nuclearsubs": 41,
    "quagmire": 42,
    "saltnegotiations": 43,
    "beartrap": 44,
    "summit": 45,
    "howilearned": 46,
    "howilearnedtostopworrying": 46,
    "junta": 47,
    "kitchendebates": 48,
    "missileenvy": 49,
    "wwby": 50,
    "wewillburyyou": 50,
    "brezhnev": 51,
    "brezhnevdoctrine": 51,
    "portuguese": 52,
    "portugueseempirecrumbles": 52,
    "southafrican": 53,
    "southafricanunrest": 53,
    "allende": 54,
    "willybrandt": 55,
    "muslimrevolution": 56,
    "abmtreaty": 57,
    "culturalrev": 58,
    "culturalrevolution": 58,
    "flowerpower": 59,
    "u2": 60,
    "u2incident": 60,
    "opec": 61,
    "lonegunman": 62,
    "colonial": 63,
    "colonialrearguards": 63,
    "panamacanal": 64,
    "panamacanalreturned": 64,
    "campdavid": 65,
    "campdavidaccords": 65,
    "puppet": 66,
    "puppetgovernments": 66,
    "grainsales": 67,
    "grainsalestosoviets": 67,
    "johnpaul": 68,
    "johnpauliielectedpope": 68,
    "deathsquads": 69,
    "latinamericandeathsquads": 69,
    "oas": 70,
    "oasfounded": 70,
    "nixon": 71,
    "nixonplaysthechinacard": 71,
    "sadat": 72,
    "sadatexpelssoviets": 72,
    "shuttle": 73,
    "shuttlediplomacy": 73,
    "voiceofamerica": 74,
    "thevoiceofamerica": 74,
    "liberation": 75,
    "liberationtheology": 75,
    "ussuri": 76,
    "ussuririverskirmish": 76,
    "asknot": 77,
    "alliance": 78,
    "allianceforprogress": 78,
    "africa": 79,
    "africascoring": 79,
    "onesmallstep": 80,
    "samerica": 81,
    "southamerica": 81,
    "southamericascoring": 81,
    "iranianhostage": 82,
    "iranianhostagecrisis": 82,
    "ironlady": 83,
    "theironlady": 83,
    "reagan": 84,
    "reaganbombslibya": 84,
    "starwars": 85,
    "northseaoil": 86,
    "reformer": 87,
    "thereformer": 87,
    "marine": 88,
    "marinebarracksbombing": 88,
    "kal007": 89,
    "KAL007": 89,
    "sovietsshootdownkal007": 89,
    "glasnost": 90,
    "glastnost": 90,
    "ortega": 91,
    "ortegaelectedinnicaragua": 91,
    "terrorism": 92,
    "irancontra": 93,
    "irancontrascandal": 93,
    "chernobyl": 94,
    "debtcrisis": 95,
    "latinamericandebtcrisis": 95,
    "teardown": 96,
    "teardownthiswall": 96,
    "evilempire": 97,
    "anevilempire": 97,
    "aldrichames": 98,
    "aldrichamesremix": 98,
    "pershing": 99,
    "pershingiideployed": 99,
    "wargames": 100,
    "solidarity": 101,
    "iraniraq": 102,
    "iraniraqwar": 102,
    "defectors": 103,
    "cambridge": 104,
    "thecambridgefive": 104,
    "specialrelation": 105,
    "specialrelationship": 105,
    "norad": 106,
    "che": 107,
    "tehran": 108,
    "ourmanintehran": 108,
    "yuri": 109,
    "yuriandsamantha": 109,
    "awacs": 110,
    "awacssaletosaudis": 110,
}

CANONICAL_COUNTRY_TO_ID: Dict[str, int] = {}
for _cid in range(84):
    _cname = ts.MapData.get_country_name(_cid)
    _slug = _cname.lower().replace(" ", "").replace("-", "").replace("/", "").replace("'", "")
    CANONICAL_COUNTRY_TO_ID[_slug] = _cid

CANONICAL_COUNTRY_TO_ID.update({
    "uk": CANONICAL_COUNTRY_TO_ID.get("unitedkingdom", 1),
    "wgermany": CANONICAL_COUNTRY_TO_ID.get("westgermany", 7),
    "egermany": CANONICAL_COUNTRY_TO_ID.get("eastgermany", 10),
    "nkorea": CANONICAL_COUNTRY_TO_ID.get("northkorea", 56),
    "skorea": CANONICAL_COUNTRY_TO_ID.get("southkorea", 57),
    "seafricanstates": CANONICAL_COUNTRY_TO_ID.get("seafricanstates", 47),
    "swafrica": CANONICAL_COUNTRY_TO_ID.get("swafrica", 49),
})
